---
# tasks file for dnsmasq

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install dnsmasq
  ansible.builtin.package:
    name: "{{ dnsmasq_packages }}"
    state: present

- name: Configure dnsmasq
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: "{{ dnsmasq_configuration_file }}"
    owner: "{{ dnsmasq_user }}"
    group: "{{ dnsmasq_group }}"
    mode: "0644"
  notify:
    - Test dnsmasq configuration
    - Restart dnsmasq

- name: Start and enable dnsmasq
  ansible.builtin.service:
    name: "{{ dnsmasq_service }}"
    state: started
    enabled: true

- name: "Configuring additional hosts file"
  tags: fp_hosts_conf
  ansible.builtin.template:
    src: hosts.j2
    dest: "{{ item.path }}"
    owner: root
    group: wheel
    mode: "0644"
  vars:
    config: "{{ item.conf }}"
  loop: "{{ dnsmasq_addn_hosts_conf }}"
  when: dnsmasq_addn_hosts_conf is defined
  notify: Reload dnsmasq
